# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kayleigh "KaleB" Bishop
title: Robotics PhD student by day, tired procrastinator by night
email: kaleb.bishop@colorado.edu
icon: https://picrew.me/image_maker/137904
cv: assets/docs/research_cv.pdf
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  kalebishop
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
    I'm  a PhD student interested in researching embodied computational models of human behavior, especially perceptual, linguistic, and social skills. 
    Using knowledge of how humans perceive and operate on the world and the social beings around them can inform the creation of more intelligent, adaptive, and communicative systems. 
    I am particularly interested in the potential application of these skills in <b>socially assistive robotics</b> and <b>robots for education</b>. 
    My other interests include human-robot interaction, natural language processing, artificial intelligence, and social learning across cultures.

content:
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Teaching grounded reading skills via an interactive robot tutor
        link: "kalebishop.github.io/assets/docs/R4L-HRI2021_Bishop.pdf"
        link_text: [PDF]
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          K. Bishop, B. Hayes and A. Roncone

          Workshop on Robots for Learning, HRI 2021



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Colorado Boulder
        caption: Fall 2020 - present
        sub_title: Ph.D. in Computer Science
        quote: >
          "Have you slept recently?" -- my advisor
        description: | # this will include new lines to allow paragraphs
          I'm in my first year of PhD study as part of the [HIRO](https://hiro-group.ronc.one/) and [CAIRO](http://cairo-lab.com/) labs here at Boulder, 
          co-advised by Profs. Alessandro Roncone and Bradley Hayes. 
          I'm also a co-investigator in the [Institute for Student-AI Teaming (ISAT)](https://outreach.colorado.edu/program/ai-institute-for-student-ai-teaming/) 
          and was awarded the Graduate School's Chancellor's Fellowship in 2020.

      - layout: left
        title: Yale University
        caption: 2016 - 2020
        sub_title: B.S. in Cognitive Science
        quote: >
          "If you like programming, why does it make you scream so much?" -- my friends
        description: | # this will include new lines to allow paragraphs
          I majored in Cognitive Science with a concentration on Mind & Computation. 
          My thesis, Grounded Natural Language for Collaborative Robotics, was advised by Prof. Brian Scassellati.  
            - GPA: 3.92/4.00
            - Graduated Magna Cum Laude, with Honors in the Major

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Graduate Researcher
        link: https://www.colorado.edu/cs/
        # link_text: boringcompany.com
        sub_title: CU Boulder Department of Computer Science
        caption: Fall 2020 - Present
        description: | # this will include new lines to allow paragraphs
          Graduate research assistant and co-investigator as part of the Human Interaction & Robotics Group 
            and the Collaborative AI & Robotics Lab.

      - layout: left
        title: Undergraduate Research Assistant
        link: scazlab.yale.edu
        # link_text: boringcompany.com
        sub_title: Yale University Department of Computer Science
        caption: Fall 2017 - Spring 2020
        description: | # this will include new lines to allow paragraphs
          Research assistant in the [Yale Social Robotics Lab](https://scazlab.yale.edu/) (aka Scazlab).

  - title: Teaching & Mentorship # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Advising Fellow
        link: https://www.matriculate.org
        link_text: matriculate.org
        sub_title: Matriculate
        caption: 2018 - 2020
        description: | # this will include new lines to allow paragraphs
          Free college advising for low-income high school students (ASC-certified)

      - layout: left
        title: First-year Counselor
        # link: https://www.matriculate.org
        # link_text: matriculate.org
        sub_title: Yale University (Timothy Dwight College)
        caption: 2019 - 2020
        description: | # this will include new lines to allow paragraphs
          Academic and residential advisor to first-year students

      - layout: left
        title: Yale Summer Session Counselor
        # link: https://www.matriculate.org
        # link_text: matriculate.org
        sub_title: Yale University
        caption: Summer 2019
        description: | # this will include new lines to allow paragraphs
          Academic and residential advisor to high school students in summer course program

      - layout: left
        title: Computer Science tutor
        # link: https://www.matriculate.org
        # link_text: matriculate.org
        sub_title: Self-employed
        caption: 2018 - 2019
        description: | # this will include new lines to allow paragraphs
          Tutored for Artificial Intelligence (Yale CPSC470) and Data Structures & Programming Techniques (Yale CPSC223)

      - layout: left
        title: ONEXYS Mathematics Leader
        link: https://onexys.yale.edu/
        link_text: onexys.yale.edu
        sub_title: Yale University
        caption: Summer 2017
        description: | # this will include new lines to allow paragraphs
          Taught college math fundamentals for incoming Yale students from low-income backgrounds





  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
